# Generated by Django 3.1 on 2020-08-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafile', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='typeoffile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
